# Syntax-highlighting / pager color scheme.
# Originally auto-generated by fish's 4.3 universal->global theme migration;
# renamed from fish_frozen_theme.fish and kept intentionally since these are
# the real color values in use, not a leftover migration artifact.

set --global fish_color_autosuggestion 626262
set --global fish_color_cancel -r
set --global fish_color_command 87d75f
set --global fish_color_comment d7d7d7
set --global fish_color_cwd green
set --global fish_color_cwd_root red
set --global fish_color_end 5fffff
set --global fish_color_error ff0000
set --global fish_color_escape 00a6b2
set --global fish_color_history_current --bold
set --global fish_color_host normal
set --global fish_color_host_remote yellow
set --global fish_color_match --background=brblue
set --global fish_color_normal normal
set --global fish_color_operator 00a6b2
set --global fish_color_param eeeeee
set --global fish_color_quote d7af5f
set --global fish_color_redirection 00afff
set --global fish_color_search_match white --background=brblack
set --global fish_color_selection white --bold --background=brblack
set --global fish_color_status red
set --global fish_color_user brgreen
set --global fish_color_valid_path --underline
set --global fish_pager_color_completion normal
set --global fish_pager_color_description B3A06D yellow
set --global fish_pager_color_prefix white --bold --underline
set --global fish_pager_color_progress brwhite --background=cyan
set --global fish_pager_color_selected_background -r
