tap 'homebrew/core'

tap 'homebrew/bundle' # gives basic brewfile capability needed by provision-mac.sh

tap 'rcmdnk/file' # a few other features for alternate brew file management
brew 'brew-file'  # but it has to be set up/initiated if desired
                  # https://homebrew-file.readthedocs.io/en/latest/

# shells and standard command line utilities
brew 'zsh'
brew 'fish'
brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'findutils'
brew 'grep'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'readline'
brew 'tree'
brew 'htop'
brew 'z'
brew 'p7zip'
brew 'lbzip2'
brew 'lz4'
brew 'unrar'
brew 'unar'
brew 'gnupg'
brew 'xz'
brew 'tldr'
brew 'zlib'
brew 'thefuck'
brew 'pv'

# meta environments
brew 'python' # brew version is backup/allows global package sandbox with pipx
brew 'pyenv'
brew 'rbenv'
brew 'ruby-build'
brew 'nodenv'
brew 'node-build'
# brew 'rustup-init' # installed in provision-mac.sh

# other programming languages
brew 'go'
brew 'r'
brew 'lua'
brew 'perl'

# network stuff
brew 'wget'
brew 'nmap'
brew 'tor'
brew 'elinks'
brew 'iperf3'
brew 'openssl'
brew 'openconnect'
brew 'wifi-password'
brew 'speedtest-cli'

# dev tools
brew 'git'
brew 'git-lfs'
brew 'mercurial'
brew 'cmake'
brew 'clang-format'
brew 'ctags'
brew 'hub'
brew 'libyaml'
brew 'ripgrep'
brew 'jq'
brew 'sqlite'
brew 'mycli'

# cask tools
tap 'vitorgalvao/tiny-scripts'
brew 'cask-repair'

# document and graphics tools
brew 'emacs'
brew 'pandoc'
brew 'multimarkdown'
brew 'sphinx-doc'
brew 'xmlto'
brew 'imagemagick'
brew 'ghostscript'
brew 'pdf2svg'
brew 'svg2png'
brew 'woff2'
brew 'pngcrush'
brew 'pngquant'
brew 'zopfli'
brew 'guetzli'
brew 'mozjpeg'
brew 'gifski'
brew 'openjpeg'
brew 'webp'

# various and sundry
brew 'hugo'
brew 'lame'
brew 'mpv'
brew 'libdvdcss'
brew 'youtube-dl'
brew 'ffmpeg'
brew 'libav'
brew 'dockutil'
brew 'trash'
brew 'pidof'
brew 'fdupes'
brew 'weechat'

# amusements!
brew 'nethack'
brew 'frotz'
brew 'solarus'

# now getting into full macOS apps
tap 'homebrew/cask-versions'
cask 'affinity-publisher-beta' # license
cask 'firefox-developer-edition'

tap 'homebrew/cask'

# dependencies to be installed first
cask 'adoptopenjdk' #imagej dependency
cask 'xquartz' # wine-stable dependency

# now cask apps
cask '1password' # license
cask 'adium'
cask 'adventure'
cask 'alfred' # license
cask 'anki'
cask 'applepi-baker'
cask 'arduino'
cask 'audio-hijack' # license
cask 'authy'
cask 'autodesk-fusion360' # education license
# cask 'backblaze' # don't use homebrew for this; upgrade will bork things
cask 'balenaetcher'
# cask 'bartender' # install/use setapp version
cask 'basictex'
cask 'bbedit' # license
cask 'bettertouchtool' # license
cask 'bitbar'
cask 'calibre'
cask 'carbon-copy-cloner' # license
cask 'cheatsheet'
# cask 'cleanmymac' # use setapp version
cask 'cyberduck'
cask 'dash' # license
# cask 'default-folder-x' # license
                          # use setapp version
cask 'devonthink' # license
cask 'dhs'
cask 'discord'
cask 'docker'
cask 'do-not-disturb'
cask 'dropbox'
cask 'firefox'
cask 'fission' # license
cask 'fluid'
cask 'flux'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'hazel'
cask 'iina'
cask 'imagej'
cask 'imageoptim'
cask 'imazing' # license
cask 'insomnia'
cask 'istat-menus' # license
cask 'itch'
cask 'ivpn'
cask 'julia'
cask 'kaleidoscope' # license
cask 'kextviewr'
cask 'keyboard-maestro' # license
cask 'kindle'
cask 'knockknock'
cask 'little-snitch' # license
cask 'macupdater'
cask 'marked' # license
cask 'microsoft-office' # license
cask 'microsoft-teams' # license
cask 'nvalt'
cask 'omnidisksweeper'
cask 'onyx' # not yet Big Sur compatible, install will fail until it is
cask 'openemu'
cask 'oversight' # CAVEAT: need to quit oversight from menu bar or else brew hangs
cask 'pacifist'
cask 'path-finder' # license
cask 'pdf-expert' # license
cask 'pdfpenpro'
cask 'phoenix'
cask 'pingplotter'
cask 'podcastmenu'
cask 'post-haste'
cask 'quitter'
cask 'r' # seem to be cran issues if I just brew the cli
cask 'resilio-sync'
cask 'rstudio'
cask 'screens' # license
cask 'scrivener' # license
cask 'send-to-kindle'
# cask 'setapp' # cask has issues, use direct app
cask 'signal'
cask 'silentknight'
cask 'skim'
cask 'skype'
cask 'soundsource' # license
cask 'swiftdefaultappsprefpane'
cask 'steam'
cask 'sublime-text'
cask 'synergy' # license/account
cask 'taskexplorer'
cask 'textexpander'
cask 'tor-browser'
cask 'tower' # edu license
cask 'transmission'
cask 'tripmode' # license
cask 'virtualbox'
cask 'visual-studio'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'wine-stable'
cask 'wwdc'
cask 'xscope'
cask 'zerobranestudio'
cask 'zoom'
cask 'zotero'

# quicklook stuff - https://github.com/markcarroll/quick-look-plugins
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'suspicious-package'

# a few monospaced fonts from caskroom
#   (others handled outside of script)
tap  'homebrew/cask-fonts'
cask 'font-inconsolata'
cask 'font-hack'
cask 'font-juliamono'

# drivers
tap  'homebrew/cask-drivers'
cask 'sonos'
cask 'ubiquiti-unifi-controller'
cask 'luna-display'
cask 'luna-secondary'
cask '8bitdo-firmware-updater'
cask 'caldigit-thunderbolt-charging'
cask 'displaylink'
cask 'logitech-options'


# and finally, stuff from the Mac App Store
brew 'mas'

mas 'Affinity Designer', id: 824171161
mas 'Affinity Photo', id: 824183456
mas 'Airmail', id: 918858936
mas 'Amphetamine', id: 937984704
mas 'BetterSnapTool', id: 417375580
mas 'Broadcasts', id: 1469995354
mas 'Cardhop', id: 1290358394
mas 'CARROT Weather', id: 993487541
mas 'Clean Text', id: 414782261
mas 'Deliveries', id: 924726344
mas 'Drafts', id: 1435957248
mas 'EtreCheck', id: 1423715984
mas 'Fantastical', id: 975937182
mas 'FruitJuice', id: 671736912
# mas 'GarageBand', id: 682658836 # these updates are tough on my net
mas 'Gemini 2', id: 1090488118
mas 'HazeOver', id: 430798174
mas 'iMovie', id: 408981434
mas 'Interact Scratchpad', id: 1199660222
mas 'iPulse', id: 1028916583
mas 'KeyKey', id: 1035137927
mas 'Keynote', id: 409183694
mas 'Mactracker', id: 430255202
mas 'Magnet', id: 441258766
mas 'MPlayerX', id: 421131143
mas 'Numbers', id: 409203825
# mas 'OneDrive', id: 823766827 #installed by office cask
mas 'Pages', id: 409201541
mas 'Pastebot', id: 1179623856
mas 'PCalc', id: 403504866
mas 'PiPifier', id: 1160374471
mas 'Pocket', id: 568494494
mas 'PopClip', id: 445189367
mas 'Slack', id: 803453959
mas 'SwitchGlass', id: 1498546559
mas 'The Unarchiver', id: 425424353
mas 'Todoist', id: 585829637
mas 'uBlock', id: 1385985095
mas 'Unclutter', id: 577085396
mas 'Wallpaper Wizard', id: 1266674560
mas 'Xcode', id: 497799835
mas 'Zen Timer', id: 1031035430
