name: scimath
channels:
  - defaults

dependencies:
    # math and visualization
    - numpy
    - scipy
    - pandas
    - tensorflow
    - matplotlib
    - seaborn
    - mpld3
    - plotly
    - vispy

