#!/usr/bin/env zsh

# A single script that monitors each of the following for updates:
#     Homebrew (command line programs) - this covers python/node/ruby too,
#       now that they're plain single-version Homebrew formulae rather
#       than asdf-managed
#     Homebrew's Casks (GUI apps)
#     Mac App Store (flakily, as the mas tool struggles at times)
#     Stable branch of Rust toolchain (via rustup, itself a brew formula -
#       see rust_check/rust_up below for why this needs its own check)
#
# Specifically does not monitor packages within script environments;
#   those might be pinned to specific versions and need to be checked
#   individually.

local -a envs=(brew cask mas rust)
local -a cmds=(check up)

if [[ $(uname -m) == 'arm64' ]]; then
  hbdir=/opt/homebrew
else
  hbdir=/usr/local
fi
bindir=$hbdir/bin

help() {
    echo "Usage: envup [check|up] [environment]"
    echo "    defaults: envup check all"
}


all_check() {
    $bindir/brew update > /dev/null 2>&1
    source $(which env_parallel.zsh)
    env_parallel --keep-order {}_check all ::: ${envs[@]}
}

all_up() {
    echo "Update individually for now."
    exit 1
}


print_check() {
    if [[ $2 != $3 ]]; then
        echo "  ⚠️   $1 latest version is $3; installed is $2."
    else
        echo "  ✅  $1 is up to date. ($2)"
    fi
}


brew_check() {
    if [[ $1 != "all" ]]; then
        $bindir/brew update > /dev/null 2>&1
    fi
    if [[ $? -ne 0 ]]; then
        echo "  ❌  Couldn’t check Homebrew packages. Internet down?"
        return
    fi
    local outBrew=$($bindir/brew outdated --formula --quiet)
    local outFmt=$(echo $outBrew | xargs | sed -e "s/ /, /g")
    local outCount=$(echo $outBrew | wc -l | xargs)
    local info=""
    if [[ ${#outBrew} == 0 ]]; then
        info="  ✅  Homebrew packages are up to date."
    elif [[ $outCount == 1 ]]; then
        info="  ⚠️   Homebrew has 1 outdated package. ($outFmt)"
    else
        info="  ⚠️   Homebrew has $outCount outdated packages. ($outFmt)"
    fi

    echo ${info} | fold -s -w $COLUMNS
}

brew_up() {
    HOMEBREW_NO_AUTO_UPDATE=1 $bindir/brew upgrade --formula -v
    $bindir/brew cleanup -s
    rm -rf $($bindir/brew --cache)
    brew_check
}


cask_check() {
    if [[ $1 != "all" ]]; then
        $bindir/brew update > /dev/null 2>&1
    fi
    if [[ $? -ne 0 ]]; then
        echo "  ❌  Couldn’t check Homebrew casks. Internet down?"
        return
    fi
    local outCask=$($bindir/brew outdated --cask --quiet)
    local outFmt=$(echo $outCask | xargs | sed -e "s/ /, /g")
    local outCount=$(echo $outCask | wc -l | xargs)
    local info=""
    if [[ ${#outCask} == 0 ]]; then
        info="  ✅  Homebrew casks are up to date."
    elif [[ $outCount == 1 ]]; then
        info="  ⚠️   Homebrew has 1 outdated cask. ($outFmt)"
    else
        info="  ⚠️   Homebrew has $outCount outdated casks. ($outFmt)"
    fi

    echo ${info} | fold -s -w $COLUMNS
}

cask_up() {
    HOMEBREW_NO_AUTO_UPDATE=1 $bindir/brew upgrade --cask -v
    # $bindir/brew cleanup
    rm -rf $($bindir/brew --cache)
    echo "  ✅  Homebrew casks are up to date."
}


mas_check() {
    # <sigh> no "--quiet" modifier for mas :-/
    local outMas=$($bindir/mas outdated | sed -E 's/^[0-9]+[[:space:]]+(.*)[[:space:]]+\([0-9.]*[[:space:]]+->[[:space:]]+[0-9.]*\)$/\1/')
    local outFmt=$(echo $outMas | paste -d🐼 -s - | sed -e "s/🐼/, /g")
    local outCount=$(echo $outMas | wc -l | xargs)
    local info=""
    if [[ ${#outMas} == 0 ]]; then
        info="  ✅  Mac App Store apps are up to date."
    elif [[ $outCount == 1 ]]; then
        info="  ⚠️   Mac App Store has 1 outdated app. ($outFmt)"
    else
        info="  ⚠️   Mac App Store has $outCount outdated apps. ($outFmt)"
    fi

    echo ${info} | fold -s -w $COLUMNS
}

mas_up() {
    $bindir/mas upgrade
    echo "  ✅  Mac App Store apps are up to date."
}


rust_check() {
    local rustStatus=$(rustup check | grep stable)
    local currentVersion=$(echo $rustStatus | sed -n -E "s/^.*: ([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+).*$/\1/p")

    local info=""
    if echo $rustStatus | grep -qi "up to date"; then
        info="  ✅  Rust is up to date. ($currentVersion)"
    else
        local newVersion=$(echo $rustStatus | sed -n -E "s/^.*-> ([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+).*$/\1/p")
        info="  ⚠️   Rust latest version is $newVersion; installed is $currentVersion."
    fi

    echo ${info} | fold -s -w $COLUMNS
}

rust_up() {
    rustup update stable
    rust_check
}


[[ $ZSH_EVAL_CONTEXT =~ :file$ ]] && sourced=1 || sourced=0
if [[ $sourced -ne 1 ]]; then
    ic_output=$(nc -z www.apple.com 80 -G2 2>&1); ic_status=$?
    if [ $ic_status -ne 0 ]; then
        echo "  😣 Doesn't look like there's a connection to the internet right now..."
        echo "     Error: ($ic_status) - $ic_output"
        exit 1
    fi

    local val=""
    local command=""
    if [[ $#@ -lt 2 ]]; then
        val="all"
    fi
    if [[ $#@ -lt 1 ]]; then
        command="check"
    fi
    if [[ $#@ -ge 2 ]]; then
        command=$1
        val=$2
    fi

    if [[ ${envs[(ie)$val]} -gt ${#envs} ]]; then
        if [[ $val != "all" ]]; then
            echo "INVALID ENVIRONMENT: $val"
            help
            exit 1
        fi
    fi

    if [[ ${cmds[(ie)$command]} -gt ${#cmds} ]]; then
        echo "INVALID COMMAND: $command"
        help
        exit 1
    fi

    ${val}_${command}
fi

